
tasks:
  - name: Install Python 3.10
    init: |
      sudo add-apt-repository ppa:deadsnakes/ppa -y
      sudo apt install python3.10 python3.10-distutils python3.10-dev -y
      curl -sSL https://install.python-poetry.org | python3 -

vscode:
  extensions:
    - streetsidesoftware.code-spell-checker
    - EditorConfig.EditorConfig
    - yzhang.markdown-all-in-one
    - DavidAnson.vscode-markdownlint
    - ms-python.python
    - redhat.vscode-yaml
    - samuelcolvin.jinjahtml
